### ISSUE TITLE
Crash upon opening Notes GUI on multiplayer server

### ISSUE THREAD

**Issue by FederalX** [MattCzyr/Notes#1] opened 2017-01-21 17:42 UTC
The mod works fine, as far as I've tested in a single player world. However, attempting to open the Notes GUI on a multiplayer server using the 1.10.2 version of the mod crashes the client. Crash log posted here: http://pastebin.com/tWkb8Xh6

**Comment by MattCzyr** [comment] 2017-01-21 22:35
Does this happen consistently, every time you try to open the GUI on a multiplayer server? Just tested it again myself and it behaved as intended. The only way I foresee this crash happening is if the client is connected to a server yet has no valid server data.

I'll add a safeguard just in case.

**Comment by FederalX** [comment] 2017-01-21 23:50
Yes, this is consistently happening every time I try opening the GUI on multiplayer. I had someone else try it too, and they were also getting consistently crashed. Perhaps it's an incompatibility with another mod?

**Comment by MattCzyr** [comment] 2017-01-22 02:20
Does the address you use to connect to the server have a port, or in other words, does it have a : symbol in it? I completely forgot that's an invalid symbol in file names. I'll get that fixed.

**Comment by MattCzyr** [comment] 2017-01-22 03:13
Should be fixed in version 1.0.1. Let me know if it's still an issue.

**Closed by MattCzyr** 2017-01-22 03:13 UTC
